### PR TITLE
added discrete maths

### PR DESCRIPTION
**Pull request by pixelmagenta**

### CODE REVIEW

**Comment by ev-br** [comment]
This is from Ю.Ю.?

**Comment by pixelmagenta** [comment]
Yes, from him via Maria Bakhanova.

**Comment by ev-br** [comment]
Good, thanks both!

**Comment by ev-br** [comment]
Aside: to keep git history clean, you can do `git fetch origin && git rebase origin/master`. Doesn't matter here, but does help in larger projects.

**Pull request merged**
